source "https://rubygems.org"

gem 'sinatra', '~> 2.0', '>= 2.0.1'
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.1'
gem 'sqlite3', '~> 1.3', '>= 1.3.13'
gem 'data_mapper', '~> 1.2'
gem 'dm-sqlite-adapter', '~> 1.2'
