source "https://rubygems.org"

gem 'sinatra', '~> 2.0', '>= 2.0.1'
gem 'sinatra-contrib', '~> 2.0', '>= 2.0.1'
gem 'pry', '~> 0.11.3'
gem 'slim', '~> 3.0', '>= 3.0.9'
gem 'sass', '~> 3.5', '>= 3.5.6'
